services:
  reverseproxy:
    image: rlaqhguse/reverseproxy:latest
    container_name: reverseproxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      if-network:
        aliases:
          - reverseproxy
    volumes:
      - /etc/letsencrypt/live/investfuture.my/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/investfuture.my/privkey.pem:/etc/nginx/certs/privkey.pem
    user: root
  react:
    image: rlaqhguse/if-fe:latest
    container_name: react
    ports:
      - "3000:80"
    networks:
      if-network:
        aliases:
          - react
networks:
  if-network:
    driver: bridge
