services:
  reverseproxy:
    image: rlaqhguse/reverseproxy:latest
    container_name: reverseproxy
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
      if-network:
        aliases:
          - reverseproxy
    volumes:
      - /etc/letsencrypt/live/investfuture.my/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/investfuture.my/privkey.pem:/etc/nginx/certs/privkey.pem
    user: root
  react:
    image: rlaqhguse/if-fe:latest
    container_name: react
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      if-network:
        aliases:
          - react
  backend:
    image: rlaqhguse/if-be:latest
    container_name: springboot
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone:ro
    networks:
      if-network:
        aliases:
          - springboot
  
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    # restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      if-network:
        aliases:
          - mariadb

networks:
  if-network:
    driver: bridge

volumes:
  mariadb-data:
