name: Deploy nginx

run-name: Deploy nginx as reverse proxy image to docker hub by ${{github.actor}}

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/reverseproxy:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Push image to Docker hub
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/reverseproxy:latest